### ISSUE TITLE
This tool does not escape quotes

### ISSUE THREAD

**Issue by SirFrostingham** [eraser1/BE_AEG#2]
It failed to translate this:
"(_this select 0) execVM "\A3\weapons_f\data\scripts\fire.sqf";"
To this:
"(_this select 0) execVM \"\A3\weapons_f\data\scripts\fire.sqf\";"

Hey, free testing is nice, eh? :)

**Comment by SirFrostingham** [comment]
Actually, the tools was running, but stopped making updates.  Not sure what happened, and closing this.

**Comment by eraser1** [comment]
I just wanted to note that the latest update may have fixed the issue where the tool stopped making updates :)
